const OK_STATUS = 200;
const CREATED_STATUS = 201;
const BAD_REQUEST_ERROR = 400;
const UNAUTHORIZED_ERROR = 401;
const FORBIDDEN_ERROR = 403;
const NOT_FOUND_ERROR = 404;
const CONFLICTING_REQUEST_ERROR = 409;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  OK_STATUS,
  CREATED_STATUS,
  BAD_REQUEST_ERROR,
  UNAUTHORIZED_ERROR,
  FORBIDDEN_ERROR,
  NOT_FOUND_ERROR,
  CONFLICTING_REQUEST_ERROR,
  INTERNAL_SERVER_ERROR,
};
